version: 2
jobs:
  build:
    working_directory: ~/midi-instruments
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - restore_cache:
          keys:
            - v1-dep-{{ .Branch }}-
            - v1-dep-master-
            - v1-dep-
      - run: yarn
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/.cache/yarn
      - run:
          name: prettier
          command: |
            yarn prettier
      - run:
          name: type checking
          command: |
            yarn tsc
      - run:
          name: obtain tree hash
          command: |
            git rev-parse HEAD: | tee /tmp/tree.hash
      - restore_cache:
          keys:
            - v1-tree-{{ checksum "/tmp/tree.hash" }}
      - run:
          name: build
          command: |
            yarn build
      - run:
          name: deploy
          command: |
            if [ "$CIRCLE_BRANCH" = master ]
            then
              yarn deploy
            fi
      - store_test_results:
          path: /tmp/circleci-test-results
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results
